import { chromium } from "@playwright/test";
const browser = await chromium.launch({ executablePath: "/usr/bin/google-chrome", args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
page.on("pageerror", (e) => errors.push("PAGEERROR: " + e.message + "\n" + (e.stack ?? "").split("\n").slice(0, 4).join("\n")));
await page.goto("http://localhost:5173/", { waitUntil: "load" }).catch((e) => errors.push("GOTO: " + e.message));
await page.waitForTimeout(1500);
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.click('[data-action="new"]');
await page.click('[data-spec-id="ai"]');
await page.click('[data-trait-id="debugger"]');
await page.click('[data-action="begin"]');
await page.waitForTimeout(6000);
const screen = await page.evaluate(() => window.__aitrainer?.getScreen?.());
const player = await page.evaluate(() => window.__aitrainer?.getPlayer?.());
const npcs = await page.evaluate(() => window.__aitrainer?.inspectNpcs?.());
console.log("SCREEN:", screen, "PLAYER:", JSON.stringify(player));
console.log("NPC STATES:", npcs ? npcs.map((n) => n.npcId + ":" + String(n.state)).join(" ") : "null");
console.log("CONSOLE ERRORS:", errors.length ? errors.join("\n---\n").slice(0, 3000) : "none");
await browser.close();
