/**
 * Shared Jev decision-layer contract types (ADR-0009 section 4, WS0).
 *
 * TYPES ONLY — this module compiles to nothing at runtime. It exists so
 * every workstream (decision core, world-tick, dialogue steering,
 * content authors, mission slice) shares one definition of what crosses
 * the decision boundary instead of re-declaring it per file.
 *
 * Semantics pinned by the ADR:
 *  - Jev is selection-only: candidates are authored; decisions select
 *    among them (D-45). No authored text is generated by the model.
 *  - Answers are a discriminated union keyed by
 *    (decisionId, subjectId, surface, questionId). A Noul answer
 *    carries `noul: number` and has NO confidence field — gating on
 *    distance from 0.5, never on confidence (ADR-0009 section 4, D-49).
 *  - No numeric deltas cross the model boundary: social reactions are
 *    bucket Choices; code maps bucket -> deltas (D-50).
 */

import type { ChatterExchange } from "../content/office-chatter";
import type { Period, ScheduleEntry } from "../content/npc-schedule";
import type { ChatterPair } from "../engine/chatter";
import type { NpcId } from "../types";

/**
 * Decision surfaces from the ADR-0009 per-surface policy table (D-60).
 * The fallback default per surface is also defined there.
 */
export type DecisionSurface =
  | "tree-opening"
  | "option-curation"
  | "reply-selection"
  | "reply-reaction"
  | "chatter-exchange"
  | "greeting"
  | "goodbye"
  | "destination"
  | "purposeful-action"
  | "argument-trigger"
  | "mission-question"
  | "mission-answer"
  | "triad-tension";

/** One authored candidate a decision may select (D-45: selection-only). */
export interface DecisionCandidate {
  id: string;
  /** Jev-facing description of the candidate (content schema v2, D-52). */
  description: string;
  /** Curation ordering hint (higher first; tie-break for Score top-4). */
  priority?: number;
  /** Option curation must never drop a requiredForProgress option. */
  requiredForProgress?: boolean;
  /** Authored baseline score (mission answers score baseScore +/- bounded). */
  baseScore?: number;
}

/** One judged actor with its candidates and pre-computed named facts. */
export interface DecisionSubject {
  /** Stable fictional actor id (D-59 allowlist — never player text). */
  id: string;
  candidates: readonly DecisionCandidate[];
  /** Pre-computed named bands ("relationship.band": "ally", ...). */
  facts: Readonly<Record<string, string | number | boolean>>;
}

/** A batched decision request (ADR-0009 section 4). */
export interface DecisionRequest {
  decisionId: string;
  /** Dialogue / session generation — part of the staleness key (D-58). */
  generation: string;
  surface: DecisionSurface;
  subjects: readonly DecisionSubject[];
  /** Per-subject namespaced projection (D-59: allowlisted state only). */
  projection: Readonly<Record<string, unknown>>;
}

/** Fields every answer carries so it can be matched and staleness-checked. */
export interface DecisionAnswerKey {
  decisionId: string;
  subjectId: string;
  surface: DecisionSurface;
  questionId: string;
}

/**
 * Discriminated decision answer (ADR-0009 section 4):
 *  - choice   — selected candidate id + confidence
 *  - score    — a score level + confidence
 *  - noul     — a bare probability in [0, 1]; NO confidence field
 *  - subset   — ordered candidate ids with confidences (for curation)
 */
export type DecisionAnswer =
  | (DecisionAnswerKey & {
      type: "choice";
      id: string;
      confidence: number;
      probabilities?: readonly number[];
    })
  | (DecisionAnswerKey & {
      type: "score";
      level: number;
      confidence: number;
      probabilities?: readonly number[];
    })
  | (DecisionAnswerKey & {
      type: "noul";
      noul: number;
    })
  | (DecisionAnswerKey & {
      type: "subset";
      ids: readonly string[];
      confidences: readonly number[];
    });

/**
 * WS0 injection seam (ADR-0009 section 3.8 / section 10, D-47).
 *
 * Every NPC decision point in `createNpcController` resolves through
 * this shape: per-controller `hooks` (options bag) -> the module-level
 * `jevDecisionHooks` holder -> the legacy picker pre-bound to the
 * controller rng. Later Jev waves install hooks; unset members fall
 * back to the legacy behavior, so an unconfigured game plays exactly
 * as before the seam existed (TAC-01 fallback equivalence).
 *
 * The fallback (legacy) implementations are pre-bound in
 * `createDefaultDecisionHooks` in `src/engine/npc-controller.ts` and
 * consume the shared rng exactly where the pre-seam call sites did.
 */
/**
 * Wire question type — one per judged question. Mirrors the four
 * DecisionAnswer primitives (choice / score / noul / subset).
 */
export type JevQuestionType = "choice" | "score" | "noul" | "subset";

/**
 * One question sent to the decision client (WS1 wire format). The
 * provider answers each question with the matching DecisionAnswer
 * primitive. Candidates carry the authored selection set (D-45) and
 * let the adapter reject answers that name an unknown candidate id.
 */
export interface JevQuestion {
  id: string;
  type: JevQuestionType;
  /** Judge-facing instructions. Fictional allowlisted content only (D-59). */
  prompt: string;
  /** Subject this question belongs to (stamped onto the answer key). */
  subjectId?: string;
  /** Authored candidates for choice / subset questions. */
  candidates?: readonly DecisionCandidate[];
  /** Subset cardinality bounds (default 0..candidates.length). */
  minSelections?: number;
  maxSelections?: number;
}

/** Token usage reported by the provider (defensive, all optional). */
export interface DecisionUsage {
  input?: number;
  output?: number;
}

/**
 * Why a request did not produce answers. 401 -> "auth", 422 ->
 * "invalid-request", 429 -> "rate-limited", 529 / 5xx ->
 * "provider-unavailable", AbortController deadline -> "timeout",
 * unparsable JSON -> "malformed", everything else -> "network".
 * "unconfigured" is returned by the unconfigured client without any
 * network activity.
 */
export type DecisionFailureReason =
  | "unconfigured"
  | "auth"
  | "invalid-request"
  | "rate-limited"
  | "provider-unavailable"
  | "timeout"
  | "malformed"
  | "network";

export interface DecisionRequestOptions {
  /** Hard deadline for the whole request (AbortController). */
  timeoutMs?: number;
  /** Retry count for transient failures. 0 by default; the ADR caps
   *  retries at 2 and allows them ONLY on the dialogue path. */
  retries?: number;
  /** Base exponential backoff delay in ms (default 250; tests use 1). */
  backoffMs?: number;
  /** Decision identity stamped onto returned answers (D-58). */
  decisionId?: string;
  /** Session / conversation generation stamped onto answers. */
  generation?: string;
  /** Surface stamped onto answers (defaults to the request's surface). */
  surface?: DecisionSurface;
}

/**
 * The ONLY thing a client request returns — request() never throws
 * past this envelope (ADR-0009 section 5). Answers whose structural
 * validation failed (unknown candidate id, missing noul field,
 * non-finite numbers, ...) are dropped and counted in rejectedCount;
 * callers treat a missing answer as "use the fallback default".
 */
export type DecisionRequestResult =
  | {
      ok: true;
      answers: readonly DecisionAnswer[];
      /** Structurally invalid answers dropped during normalization. */
      rejectedCount: number;
      usage: DecisionUsage;
      model: string;
    }
  | {
      ok: false;
      reason: DecisionFailureReason;
      /** Human-readable context. NEVER contains the API key (D-59). */
      detail?: string;
    };

/**
 * Injectable decision client (ADR-0009 section 3.1). Implementations:
 * OpenRouter adapter (WS1), fake client (tests), unconfigured client.
 * request() resolves to a DecisionRequestResult and never rejects.
 */
export interface DecisionClient {
  isConfigured(): boolean;
  request(
    state: Readonly<Record<string, unknown>>,
    questions: readonly JevQuestion[],
    opts?: DecisionRequestOptions,
  ): Promise<DecisionRequestResult>;
}

export interface DecisionHooks {
  /** Morning greeting bubble line (D-60: legacy pool pick fallback). */
  pickMorningGreeting?: (npcId: NpcId) => string;
  /** Evening goodbye bubble line (D-60: legacy pool pick fallback). */
  pickEveningGoodbye?: (npcId: NpcId) => string;
  /**
   * Which nearby pair starts a chatter exchange. Receives every
   * eligible pair; returning null means "no conversation now".
   * Legacy fallback: uniform random pick (pickPair).
   */
  pickChatterPair?: (pairs: readonly ChatterPair[]) => ChatterPair | null;
  /** Who inside the chosen pair speaks first. Legacy: chattiness-weighted roll. */
  pickChatterStarter?: (a: string, b: string) => string;
  /**
   * Which authored exchange the starter says. Receives the active pool
   * (office or lunch chatter) as the candidate list so a steered
   * implementation can choose among all exchanges. Legacy:
   * topic-affinity-filtered uniform pick (pickExchange).
   */
  pickChatterExchange?: (
    pool: readonly ChatterExchange[],
    starterId: string,
  ) => ChatterExchange;
  /**
   * Per-period random destination roll (events.ts path). Null = stay
   * at the desk, matching the legacy `pickRandomDestination` contract.
   * Legacy fallback: the weighted role rng in npc-schedule.ts.
   */
  pickRandomDestination?: (npcId: NpcId, period: Period) => ScheduleEntry | null;
}
