/**
 * Shared Jev decision-layer contract types (ADR-0009 section 4, WS0).
 *
 * TYPES ONLY — this module compiles to nothing at runtime. It exists so
 * every workstream (decision core, world-tick, dialogue steering,
 * content authors, mission slice) shares one definition of what crosses
 * the decision boundary instead of re-declaring it per file.
 *
 * Semantics pinned by the ADR:
 *  - Jev is selection-only: candidates are authored; decisions select
 *    among them (D-45). No authored text is generated by the model.
 *  - Answers are a discriminated union keyed by
 *    (decisionId, subjectId, surface, questionId). A Noul answer
 *    carries `noul: number` and has NO confidence field — gating on
 *    distance from 0.5, never on confidence (ADR-0009 section 4, D-49).
 *  - No numeric deltas cross the model boundary: social reactions are
 *    bucket Choices; code maps bucket -> deltas (D-50).
 */

import type { ChatterExchange } from "../content/office-chatter";
import type { Period, ScheduleEntry } from "../content/npc-schedule";
import type { ChatterPair } from "../engine/chatter";
import type { NpcId } from "../types";

/**
 * Decision surfaces from the ADR-0009 per-surface policy table (D-60).
 * The fallback default per surface is also defined there.
 */
export type DecisionSurface =
  | "tree-opening"
  | "option-curation"
  | "reply-selection"
  | "reply-reaction"
  | "chatter-exchange"
  | "greeting"
  | "goodbye"
  | "destination"
  | "purposeful-action"
  | "argument-trigger"
  | "mission-question"
  | "mission-answer"
  | "triad-tension";

/** One authored candidate a decision may select (D-45: selection-only). */
export interface DecisionCandidate {
  id: string;
  /** Jev-facing description of the candidate (content schema v2, D-52). */
  description: string;
  /** Curation ordering hint (higher first; tie-break for Score top-4). */
  priority?: number;
  /** Option curation must never drop a requiredForProgress option. */
  requiredForProgress?: boolean;
  /** Authored baseline score (mission answers score baseScore +/- bounded). */
  baseScore?: number;
}

/** One judged actor with its candidates and pre-computed named facts. */
export interface DecisionSubject {
  /** Stable fictional actor id (D-59 allowlist — never player text). */
  id: string;
  candidates: readonly DecisionCandidate[];
  /** Pre-computed named bands ("relationship.band": "ally", ...). */
  facts: Readonly<Record<string, string | number | boolean>>;
}

/** A batched decision request (ADR-0009 section 4). */
export interface DecisionRequest {
  decisionId: string;
  /** Dialogue / session generation — part of the staleness key (D-58). */
  generation: string;
  surface: DecisionSurface;
  subjects: readonly DecisionSubject[];
  /** Per-subject namespaced projection (D-59: allowlisted state only). */
  projection: Readonly<Record<string, unknown>>;
}

/** Fields every answer carries so it can be matched and staleness-checked. */
export interface DecisionAnswerKey {
  decisionId: string;
  subjectId: string;
  surface: DecisionSurface;
  questionId: string;
}

/**
 * Discriminated decision answer (ADR-0009 section 4):
 *  - choice   — selected candidate id + confidence
 *  - score    — a score level + confidence
 *  - noul     — a bare probability in [0, 1]; NO confidence field
 *  - subset   — ordered candidate ids with confidences (for curation)
 */
export type DecisionAnswer =
  | (DecisionAnswerKey & {
      type: "choice";
      id: string;
      confidence: number;
      probabilities?: readonly number[];
    })
  | (DecisionAnswerKey & {
      type: "score";
      level: number;
      confidence: number;
      probabilities?: readonly number[];
    })
  | (DecisionAnswerKey & {
      type: "noul";
      noul: number;
    })
  | (DecisionAnswerKey & {
      type: "subset";
      ids: readonly string[];
      confidences: readonly number[];
    });

/**
 * WS0 injection seam (ADR-0009 section 3.8 / section 10, D-47).
 *
 * Every NPC decision point in `createNpcController` resolves through
 * this shape: per-controller `hooks` (options bag) -> the module-level
 * `jevDecisionHooks` holder -> the legacy picker pre-bound to the
 * controller rng. Later Jev waves install hooks; unset members fall
 * back to the legacy behavior, so an unconfigured game plays exactly
 * as before the seam existed (TAC-01 fallback equivalence).
 *
 * The fallback (legacy) implementations are pre-bound in
 * `createDefaultDecisionHooks` in `src/engine/npc-controller.ts` and
 * consume the shared rng exactly where the pre-seam call sites did.
 */
export interface DecisionHooks {
  /** Morning greeting bubble line (D-60: legacy pool pick fallback). */
  pickMorningGreeting?: (npcId: NpcId) => string;
  /** Evening goodbye bubble line (D-60: legacy pool pick fallback). */
  pickEveningGoodbye?: (npcId: NpcId) => string;
  /**
   * Which nearby pair starts a chatter exchange. Receives every
   * eligible pair; returning null means "no conversation now".
   * Legacy fallback: uniform random pick (pickPair).
   */
  pickChatterPair?: (pairs: readonly ChatterPair[]) => ChatterPair | null;
  /** Who inside the chosen pair speaks first. Legacy: chattiness-weighted roll. */
  pickChatterStarter?: (a: string, b: string) => string;
  /**
   * Which authored exchange the starter says. Receives the active pool
   * (office or lunch chatter) as the candidate list so a steered
   * implementation can choose among all exchanges. Legacy:
   * topic-affinity-filtered uniform pick (pickExchange).
   */
  pickChatterExchange?: (
    pool: readonly ChatterExchange[],
    starterId: string,
  ) => ChatterExchange;
  /**
   * Per-period random destination roll (events.ts path). Null = stay
   * at the desk, matching the legacy `pickRandomDestination` contract.
   * Legacy fallback: the weighted role rng in npc-schedule.ts.
   */
  pickRandomDestination?: (npcId: NpcId, period: Period) => ScheduleEntry | null;
}
